# version: "3.8"

services:
  backend:
    image: pavelkuzia/portfolio.ecommerce.backend.springboot:latest
    ports:
      - "8005:8005"
    environment:
      - ENV_AWS_RDS_ENDPOINT=${ENV_AWS_RDS_ENDPOINT}
      - ENV_PASSWORD_RDS=${ENV_PASSWORD_RDS}
      - ENV_USERNAME_RDS=${ENV_USERNAME_RDS}
      - FRONTEND_URL=${ENV_FRONTEND_URL}
      - FRONTEND_PORT=${ENV_FRONTEND_PORT}
      - ENV_STAGE=prod
      # - ENV_FRONTEND_URL=${ENV_FRONTEND_URL}
      # - ENV_FRONTEND_PORT=${ENV_FRONTEND_PORT}
    networks:
      - app-network

  frontend:
    image: pavelkuzia/portfolio.ecommerce.frontend.angular:latest
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
