ARG NODE_VERSION=24-bookworm-slim
# ARG NGINX_VERSION=alpine3.21

FROM node:${NODE_VERSION} AS build

WORKDIR /app

COPY . .

RUN npm ci

COPY . .

RUN npm install -g @angular/cli@19.0.7
RUN ng build --configuration development


FROM nginx:alpine
EXPOSE 80
COPY --from=build /app/dist/angular-ecommerce/browser /usr/share/nginx/html

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf