# build jar file #
FROM maven:3.9.9-eclipse-temurin-23 AS build

WORKDIR /app

RUN echo "hello"

COPY ./springboot.backend/pom.xml .
COPY ./springboot.backend/src ./src

RUN mvn clean install -DskipTests -q

FROM openjdk:23-jdk

WORKDIR /app

COPY --from=build app/target/portfolio.ecommerce.backend.jar backend.jar

EXPOSE 8005

ENV ENV_BACKEND_PORT=8005

ENV ENV_AWS_RDS_ENDPOINT=edu-aws-db.cbu6mq86qkdr.eu-north-1.rds.amazonaws.com
ENV ENV_USERNAME_RDS=postgres
ENV ENV_PASSWORD_RDS=FmC0cThSogj0n23l8tJE
ENV ENV_PORT_RDS=5432
ENV ENV_DB_NAME=postgres

ENV ENV_STAGE=prod

ENV VERSION=0.0.1

ENV ANGULAR_PORT=4200
ENV ANGULAR_URL=http://localhost

CMD ["java", "-jar", "backend.jar"]