name: Java CI/CD with Maven

on:
  push:
    branches: ["main"]

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: starting copy job
        run: echo "Copy Job has been started"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy docker compose file to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "./docker-compose-prod.yml"
          target: "/home/ec2-user/"
