name: Example establish connection to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.PUBLIC_EC2_HOST_IP }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Establishing connection to EC2 instance"
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem 
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} << 'EOF'
          echo "Successfully connected to EC2 instance!"
          echo "Current directory: $(pwd)"
          echo "Listing home directory:"
          ls
