name: Java CI/CD with Maven

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: |
          mvn -f /springboot.backend/pom.xml clean install -DskipTests -q
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./springboot.backend/Dockerfile
          push: true
          tags: pavelkuzia/portfolio.ecommerce.backend.springboot:latest
      - name: congratulations on finishing successfully
        run: echo "Finished pushing new image to Docker Hub"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Establishing connection to EC2 instance"
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem 
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} << 'EOF'
          echo "Successfully connected to EC2 instance!"
          echo "Current directory: $(pwd)"
          echo "Listing home directory:"
          ls
          echo "Pull Image from docker hub"
          sudo docker pull pavelkuzia/portfolio.ecommerce.backend.springboot:latest
          echo "Delete old container"
          sudo docker rm -f ecommerce-container
          echo "Run Docker Image"
          sudo docker run -d -p 8005:8005 --name ecommerce-container pavelkuzia/portfolio.ecommerce.backend.springboot:latest
